title:            Justin Rummel . com
author:           Justin Rummel # for Octopress Feed gem
description:      Professional Bio/Resume site for Justin Rummel
disqus_shortname: justinrummel
reading_time:     false
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# or https://www.justinrummel.com
url:              https://www.justinrummel.com

# Owner/author information
owner:
  name:           Justin Rummel
  avatar:         me2-small.jpg
  bio:            "Professional Bio/Resume site for Justin Rummel"
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        justinrummel
  facebook:       
  github:         justinrummel
  stackexchange:  
  linkedin:       justinrummel
  instagram:      
  flickr:         
  tumblr:         
  google_plus:    +JustinRummel-co
  rss:            feeds.feedburner.com/jr

# Background image to be tiled on all pages
background: 

# Header image to be on all posts
image:
  feature: abstract-4.jpg
  credit: dargadgetz
  creditlink: http://www.dargadgetz.com/ios-8-abstract-wallpaper-pack-for-iphone-5s-5c-and-ipod-touch-retina/

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-41781912-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Google Adsense in adsense.html section
ad-client: ca-pub-9983565238165896 
ad-slot: 3397540349
ad-index: 4095544340

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess", "robots.txt", "atom.xml"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# Default extensions.  Placing here b/c the "octopress new draft is not looking for the file extension in _octopress.yml"
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: post

lunr_search:
  js_dir: "assets/js/lunr"
  min_length: 3
  excludes: [feed.xml, atom.xml, robots.txt, sitemap.xml, 404.html, favicon.ico, favicon.png, tags, posts, bio, resume]
